### ISSUE TITLE
User creation from Reconmap does not create password in Keycloak and role is wrong

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#121]
Hi again ;)

Always on the latest release.

When you add a new user from reconmap, it is correctly created in **Keycloak** but with no password.
So the user can't login.

Solution was to connect to the **Keycloak admin console**, select **Users**, **Credentials** tab and set a password for the user.
Then you should see a password line and you can connect to reconmap with this user.
![image](https://user-images.githubusercontent.com/1230954/194110700-f1155473-1313-491e-b4c7-1c72a888a455.png)

The keycloak admin console is located at this URL
https://{docker-compose-value-KC_HOSTNAME}/admin/master/console/#/

If admin console page is blank check this issue #120 

However, although you can connect to reconmap, the role does not seem to work.
Here I create an **administrator** user, and the web UI seems quite limited, **like a simple user**.
And there is no profile button in the above right.

![image](https://user-images.githubusercontent.com/1230954/194111300-bbd1648f-1989-417c-9609-6395527dc760.png)

Maybe I miss something, but this should work flawlessly no ?

Also in logfile these errors are present while user is accessing the web UI, on each request.
```
[2022-10-05T16:21:01.577342+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.577671+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.577768+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.582724+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.582983+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.583067+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.590859+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.591185+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.591820+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.614170+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.614433+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.614604+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.615286+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.615562+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.615701+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.616132+00:00] http.WARNING: Undefined property: stdClass::$web-client (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.616312+00:00] http.WARNING: Attempt to read property "roles" on null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
[2022-10-05T16:21:01.616429+00:00] http.WARNING: Trying to access array offset on value of type null (2) on /var/www/webapp/src/Http/AuthMiddleware.php:61 [] []
```
So something is missing :(

**Comment by psyray** [comment]
I'm adding some research I made

By default in Keycloak, admin have the following role :
- administrator
- manage-account
- view-profile

When a user is created he has the following role :
- default-roles-reconmap

But in the keycloak admin, there is no way to add the role given to the admin.
Only 3 roles are available

![image](https://user-images.githubusercontent.com/1230954/194116802-f54fda8b-ca51-4255-8305-27afcff858f3.png)

I've check in the Keycloak DB, in the **KEYCLOAK_ROLE** and the administrator role are dependant of a specific realm, not the **reconmap** realm, so it explains why the role are not displayed.

**Comment by santiagolizardo** [comment]
Hi @psyray ; Thanks for reporting this problem. This has now been resolved. You would need new images for the API, Web client and Keycloak. Regards

**Comment by psyray** [comment]
Thanks.
I've tried to create a user but It returns a 500 error
```
[2022-10-19T18:25:13.134492+00:00] http.WARNING: Undefined array key 1 (2) on /var/www/webapp/src/Services/KeycloakService.php:56 [] []
[2022-10-19T18:25:13.176150+00:00] http.ERROR: Server error: `POST https://domain.tld/admin/realms/reconmap/users` resulted in a `500 Internal Server Error` response: {"error":"unknown_error"}  [] []
```
Where can I have a more detailed error ?

**Comment by psyray** [comment]
Found
```
keycloak_1    | 2022-10-19 18:56:56,693 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.RuntimeException: Unable to find group specified by path: administrator-group
keycloak_1    | 	at org.keycloak.models.utils.RepresentationToModel.createGroups(RepresentationToModel.java:1900)
keycloak_1    | 	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:161)
keycloak_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak_1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak_1    | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
keycloak_1    | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak_1    | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak_1    | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak_1    | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak_1    | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak_1    | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak_1    | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1    | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak_1    | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak_1    | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
keycloak_1    | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
keycloak_1    | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
keycloak_1    | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
keycloak_1    | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1    | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
keycloak_1    | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
keycloak_1    | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1    | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
keycloak_1    | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
keycloak_1    | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1    | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1    | 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
keycloak_1    | 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
keycloak_1    | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
keycloak_1    | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
keycloak_1    | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
keycloak_1    | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak_1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak_1    | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak_1    | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak_1    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak_1    | 	at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1    |
```

**Comment by psyray** [comment]
https://github.com/keycloak/keycloak/issues/12640

**Comment by psyray** [comment]
I've created the groups by hands from keycloak admin according to your [modified realm.json config file](https://github.com/reconmap/keycloak-custom/commit/0e1d66de641d5837a2686d38ab93a046406ea0e6) and now it works.

I think it misses something to apply modification to database for an existing installation

![image](https://user-images.githubusercontent.com/1230954/196782892-01fdfe12-6934-4cfc-bfba-4819acd6a215.png)
![image](https://user-images.githubusercontent.com/1230954/196783009-dea06299-a35d-4feb-ae56-9b61ffcc9b7f.png)
![image](https://user-images.githubusercontent.com/1230954/196783119-6856e2fb-9962-48af-9ce7-0b58e86a4317.png)
![image](https://user-images.githubusercontent.com/1230954/196783177-144e50b5-2e28-47dc-9777-180001f46927.png)
![image](https://user-images.githubusercontent.com/1230954/196783266-6f81449e-3289-41b7-9ccb-05aaf7104e45.png)
